services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    env_file: ./.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/product
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:18.1
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: product
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  pg_data: